// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk77ZFTq0W2CfAL4BEsqYhSb5nBRCLWWg',
    appId: '1:402774384012:web:2f03e20620aaf1d0068aa9',
    messagingSenderId: '402774384012',
    projectId: 'webrtc-a9dca',
    authDomain: 'webrtc-a9dca.firebaseapp.com',
    storageBucket: 'webrtc-a9dca.appspot.com',
    measurementId: 'G-0MY23V7DLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCyiWuxynof2V4osNyBpiWEz4qoOyZMow',
    appId: '1:402774384012:android:50bb0c679328330f068aa9',
    messagingSenderId: '402774384012',
    projectId: 'webrtc-a9dca',
    storageBucket: 'webrtc-a9dca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBemyRBw6GCDr1sRUf1UH0HafdAS0AeIRU',
    appId: '1:402774384012:ios:a94d996faeb5546e068aa9',
    messagingSenderId: '402774384012',
    projectId: 'webrtc-a9dca',
    storageBucket: 'webrtc-a9dca.appspot.com',
    iosClientId: '402774384012-a1q2rlfrpjhgqvdorep1h3gjnjfa2bnn.apps.googleusercontent.com',
    iosBundleId: 'com.mbilarus.webrtc',
  );
}
